apiVersion: v1
kind: DeploymentConfig
metadata:
  annotations:
    kompose.cmd: kompose -f ../../production-ci.yml --provider OpenShift convert
    kompose.version: 1.18.0 (06a2e56)
  creationTimestamp: null
  labels:
    io.kompose.service: automation-hub-backend
  name: automation-hub-backend
spec:
  replicas: 1
  selector:
    io.kompose.service: automation-hub-backend
  strategy:
    resources: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: automation-hub-backend
    spec:
      containers:
      - image: ' '
        name: automation-hub-backend
        ports:
        - containerPort: 8081
        resources: {}
      restartPolicy: Always
  test: false
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - automation-hub-backend
      from:
        kind: ImageStreamTag
        name: automation-hub-backend:latest
    type: ImageChange
status: {}
