apiVersion: v1
kind: ImageStream
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: automation-hub-backend
  name: automation-hub-backend
spec:
  tags:
  - annotations: null
    from:
      kind: DockerImage
      name: registry.insights-dev.openshift.com/automation-hub-ci/automation-hub-backend
    generation: null
    importPolicy: {}
    name: latest
status:
  dockerImageRepository: ""
