apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -f ../../production-ci.yml --provider OpenShift convert
    kompose.version: 1.18.0 (06a2e56)
  creationTimestamp: null
  labels:
    io.kompose.service: automation-hub-backend
  name: automation-hub-backend
spec:
  ports:
  - name: "8081"
    port: 8081
    targetPort: 8081
  selector:
    io.kompose.service: automation-hub-backend
status:
  loadBalancer: {}
