apiVersion: v1
kind: ImageStream
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: galaxy-api
  name: galaxy-api
spec:
  tags:
  - annotations: null
    from:
      kind: DockerImage
      name: registry.insights-dev.openshift.com/automation-hub-ci/galaxy-api
    generation: null
    importPolicy: {}
    name: latest
status:
  dockerImageRepository: ""
