apiVersion: v1
kind: ImageStream
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: pulp-worker
  name: pulp-worker
spec:
  tags:
  - annotations: null
    from:
      kind: DockerImage
      name: registry.insights-dev.openshift.com/automation-hub-ci/pulp-worker
    generation: null
    importPolicy: {}
    name: latest
status:
  dockerImageRepository: ""
