apiVersion: v1
kind: ImageStream
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: pulp-resource-manager
  name: pulp-resource-manager
spec:
  tags:
  - annotations: null
    from:
      kind: DockerImage
      name: registry.insights-dev.openshift.com/automation-hub-ci/pulp
    generation: null
    importPolicy: {}
    name: latest
status:
  dockerImageRepository: ""
