apiVersion: v1
kind: DeploymentConfig
metadata:
  annotations:
    kompose.cmd: kompose -f ../../production-prod.yml --provider OpenShift convert
    kompose.version: 1.18.0 (06a2e56)
  creationTimestamp: null
  labels:
    io.kompose.service: galaxy-api
  name: galaxy-api
spec:
  replicas: 1
  selector:
    io.kompose.service: galaxy-api
  strategy:
    resources: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: galaxy-api
    spec:
      containers:
      - env:
        - name: GALAXY_DB_HOST
          valueFrom:
            configMapKeyRef:
              key: GALAXY_DB_HOST
              name: galaxy-api-env--production--galaxy-api
        - name: GALAXY_DB_PASSWORD
          valueFrom:
            configMapKeyRef:
              key: GALAXY_DB_PASSWORD
              name: galaxy-api-env--production--galaxy-api
        - name: GALAXY_DEBUG
          valueFrom:
            configMapKeyRef:
              key: GALAXY_DEBUG
              name: galaxy-api-env--production--galaxy-api
        - name: GALAXY_SECRET_KEY
          valueFrom:
            configMapKeyRef:
              key: GALAXY_SECRET_KEY
              name: galaxy-api-env--production--galaxy-api
        - name: POSTGRESQL_DATABASE
          valueFrom:
            configMapKeyRef:
              key: POSTGRESQL_DATABASE
              name: galaxy-api-env--production--postgres
        - name: POSTGRESQL_HOST
          valueFrom:
            configMapKeyRef:
              key: POSTGRESQL_HOST
              name: galaxy-api-env--production--postgres
        - name: POSTGRESQL_PASSWORD
          valueFrom:
            configMapKeyRef:
              key: POSTGRESQL_PASSWORD
              name: galaxy-api-env--production--postgres
        - name: POSTGRESQL_PORT
          valueFrom:
            configMapKeyRef:
              key: POSTGRESQL_PORT
              name: galaxy-api-env--production--postgres
        - name: POSTGRESQL_USER
          valueFrom:
            configMapKeyRef:
              key: POSTGRESQL_USER
              name: galaxy-api-env--production--postgres
        image: ' '
        name: galaxy-api
        ports:
        - containerPort: 8000
        resources: {}
      restartPolicy: Always
  test: false
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - galaxy-api
      from:
        kind: ImageStreamTag
        name: galaxy-api:latest
    type: ImageChange
status: {}
