apiVersion: v1
kind: ImageStream
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: postgres
  name: postgres
spec:
  tags:
  - annotations: null
    from:
      kind: DockerImage
      name: registry.access.redhat.com/rhscl/postgresql-96-rhel7
    generation: null
    importPolicy: {}
    name: latest
status:
  dockerImageRepository: ""
