apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -f ../../production-prod.yml --provider OpenShift convert
    kompose.version: 1.18.0 (06a2e56)
  creationTimestamp: null
  labels:
    io.kompose.service: pulp-content-app
  name: pulp-content-app
spec:
  ports:
  - name: "5003"
    port: 5003
    targetPort: 24816
  selector:
    io.kompose.service: pulp-content-app
status:
  loadBalancer: {}
