apiVersion: v1
kind: ImageStream
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: pulp-content-app
  name: pulp-content-app
spec:
  tags:
  - annotations: null
    from:
      kind: DockerImage
      name: registry.insights.openshift.com/automation-hub-ci/pulp-content-app
    generation: null
    importPolicy: {}
    name: latest
status:
  dockerImageRepository: ""
