#!/bin/sh

set -o errexit
set -o pipefail
set -o nounset


if [ -z "${POSTGRESQL_USER}" ]; then
    base_postgres_image_default_user='postgres'
    export POSTGRESQL_USER="${base_postgres_image_default_user}"
fi
export DATABASE_URL="postgres://${POSTGRESQL_USER}:${POSTGRESQL_PASSWORD}@${POSTGRESQL_HOST}:${POSTGRESQL_PORT}/${POSTGRESQL_DATABASE}"

postgres_ready() {
python << END
import sys

import psycopg2

try:
    psycopg2.connect(
        dbname="${POSTGRESQL_DATABASE}",
        user="${POSTGRESQL_USER}",
        password="${POSTGRESQL_PASSWORD}",
        host="${POSTGRESQL_HOST}",
        port="${POSTGRESQL_PORT}",
    )
except psycopg2.OperationalError as e:
    print(e)
    sys.exit(-1)
sys.exit(0)

END
}
until postgres_ready; do
  >&2 echo 'Waiting for PostgreSQL to become available...'
  sleep 1
done
>&2 echo 'PostgreSQL is available'

exec "$@"
