#!/bin/sh

set -o errexit
set -o pipefail
set -o nounset


django-admin migrate
uwsgi --socket :8000 --chdir /code --wsgi-file galaxy-api/galaxy_api/wsgi.py --master --processes 4 --threads 2 -b 32768
